import { PostRecord } from "@/lib/types";

const now = Date.now();

const BASE = {
  author_id: null,
  author: null,
  is_user_created: false,
  tags: [],
  views_count: 0,
  audio_track: null,
  reactions_summary: { sparked: 0, fired_up: 0, bookmarked: 0 },
  user_reactions: [],
  comments_count: 0,
};

const fallbackPosts: PostRecord[] = [
  // ── MINDSET (6) ──────────────────────────────────────────
  {
    ...BASE,
    id: "fallback-1",
    title: "Stop solving imaginary problems",
    content: [
      "Most stress starts with scenarios that never happen.",
      "Write down the next real action before your mind spirals.",
      "Energy grows when your focus becomes concrete.",
      "Clarity beats intensity every single day.",
    ],
    category: "Mindset",
    source: "Daily Practice",
    image_url:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
    gradient: "aurora",
    created_at: new Date(now).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-5",
    title: "High performers protect their mornings",
    content: [
      "The first hour decides whether you react or create.",
      "Avoid instant inputs before your own priorities are clear.",
      "Start with one task that compounds over time.",
      "Momentum is easier to keep than to rebuild later.",
    ],
    category: "Mindset",
    source: "Focus Notes",
    image_url:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    gradient: "sunset",
    created_at: new Date(now - 60_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-7",
    title: "Confidence is a side effect of kept promises",
    content: [
      "Every time you follow through on a plan, your self-trust compounds.",
      "Start with promises small enough that failure feels impossible.",
      "Confidence is not about believing you are great — it is about knowing you are reliable.",
      "The gap between who you are and who you want to be closes one kept commitment at a time.",
    ],
    category: "Mindset",
    source: "Self-Trust Lab",
    image_url: null,
    gradient: "royal",
    created_at: new Date(now - 120_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-8",
    title: "Discipline feels heavy until it becomes identity",
    content: [
      "You do not rise to the level of your goals — you fall to the level of your systems.",
      "Stop negotiating with yourself every morning; pre-decide the night before.",
      "The person who needs motivation every day has a design problem, not a willpower problem.",
      "Build your environment so the default action is the right one.",
    ],
    category: "Mindset",
    source: "Behavioral Design",
    image_url: null,
    gradient: "ember",
    created_at: new Date(now - 180_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-9",
    title: "Your inner critic is using outdated data",
    content: [
      "The voice telling you that you cannot do it is referencing a version of you that no longer exists.",
      "Rewrite the narrative: list three hard things you have already survived.",
      "Treat self-doubt like a notification — acknowledge it, then swipe it away.",
      "Growth is quiet; your brain notices failures louder than wins.",
    ],
    category: "Mindset",
    source: "Cognitive Reframe",
    image_url:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    gradient: "ocean",
    created_at: new Date(now - 240_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-10",
    title: "Rest is not the opposite of ambition",
    content: [
      "Burnout does not prove you worked hard — it proves you ignored signals.",
      "Schedule rest like you schedule meetings: non-negotiable blocks.",
      "Creative breakthroughs almost never happen at a desk; they happen on walks.",
      "The most productive thing you can do some days is absolutely nothing.",
    ],
    category: "Mindset",
    source: "Sustainable Performance",
    image_url: null,
    gradient: "aurora",
    created_at: new Date(now - 300_000).toISOString(),
  },

  // ── GYM (6) ──────────────────────────────────────────────
  {
    ...BASE,
    id: "fallback-2",
    title: "Muscle comes from boring consistency",
    content: [
      "The winning plan is the one you can repeat next week.",
      "Track your main lifts and add tiny improvements.",
      "Missed workouts matter less than quitting after one miss.",
      "Recovery is part of the program, not an excuse from it.",
    ],
    category: "Gym",
    source: "Coaching Note",
    image_url:
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80",
    gradient: "ember",
    created_at: new Date(now - 360_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-11",
    title: "Progressive overload is the only law",
    content: [
      "If the weight, reps, or sets are not increasing over months, you are maintaining — not building.",
      "Add 2.5 lbs per session on compounds; micro-plates exist for a reason.",
      "When linear gains stall, wave your intensity — two hard weeks, one easy week.",
      "A training log is more valuable than any supplement stack.",
    ],
    category: "Gym",
    source: "Strength Fundamentals",
    image_url:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
    gradient: "ember",
    created_at: new Date(now - 420_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-12",
    title: "The gym is a practice in showing up",
    content: [
      "On bad days, just get through the warm-up — momentum usually takes over.",
      "Nobody at the gym is judging you; everyone is too busy fighting their own battle.",
      "Consistency at 70% effort beats perfection at 100% effort twice a month.",
      "Your worst workout still beats the one that did not happen.",
    ],
    category: "Gym",
    source: "Mindset Coach",
    image_url: null,
    gradient: "sunset",
    created_at: new Date(now - 480_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-13",
    title: "Sleep is your strongest anabolic",
    content: [
      "Growth hormone peaks during deep sleep — cutting sleep literally cuts gains.",
      "Seven to nine hours is non-negotiable if you are training seriously.",
      "A cool, dark room and consistent bedtime do more than most pre-workouts.",
      "Track your sleep quality for two weeks and watch your lifts respond.",
    ],
    category: "Gym",
    source: "Recovery Science",
    image_url: null,
    gradient: "royal",
    created_at: new Date(now - 540_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-14",
    title: "Warm up like your joints depend on it",
    content: [
      "Five minutes of targeted warm-up prevents months of forced rest.",
      "Band pull-aparts and hip circles cost nothing and protect everything.",
      "If you skip warm-ups in your twenties, your thirties will send the bill.",
      "Think of warm-ups as earning the right to lift heavy today.",
    ],
    category: "Gym",
    source: "Longevity Training",
    image_url:
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80",
    gradient: "forest",
    created_at: new Date(now - 600_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-15",
    title: "Compound lifts build more than muscle",
    content: [
      "Squats, deadlifts, and presses train coordination, stability, and mental toughness at once.",
      "Machines are fine for accessories, but free weights should form your foundation.",
      "Learning to brace your core under load transfers to every physical task in life.",
      "Master the basics for two years before chasing advanced programs.",
    ],
    category: "Gym",
    source: "Barbell Basics",
    image_url: null,
    gradient: "aurora",
    created_at: new Date(now - 660_000).toISOString(),
  },

  // ── DIET (6) ──────────────────────────────────────────────
  {
    ...BASE,
    id: "fallback-3",
    title: "Diet success starts with easier defaults",
    content: [
      "Build meals around protein first and snacks get quieter.",
      "If healthy food is visible, decision fatigue drops fast.",
      "You do not need perfect macros to make progress.",
      "Simple meals beat elaborate plans you never repeat.",
    ],
    category: "Diet",
    source: "Nutrition Guide",
    image_url:
      "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80",
    gradient: "forest",
    created_at: new Date(now - 720_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-16",
    title: "Protein is the lever — pull it first",
    content: [
      "Aim for 0.7-1g per pound of bodyweight; everything else is secondary.",
      "Front-load protein at breakfast and lunch so dinner is not a scramble.",
      "Greek yogurt, eggs, chicken thighs, and canned fish are your budget staples.",
      "If you hit protein, your cravings for junk naturally quiet down.",
    ],
    category: "Diet",
    source: "Macro Foundations",
    image_url: null,
    gradient: "ocean",
    created_at: new Date(now - 780_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-17",
    title: "Meal prep is a Sunday investment that pays all week",
    content: [
      "Cook two proteins, two carbs, and chop vegetables — mix and match for five days.",
      "Batch cooking takes 90 minutes and saves 5+ hours of decision-making.",
      "Invest in quality containers; bad containers kill meal prep habits faster than laziness.",
      "Prep is not about perfection — a mediocre prepped meal beats a skipped one.",
    ],
    category: "Diet",
    source: "Practical Nutrition",
    image_url:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80",
    gradient: "forest",
    created_at: new Date(now - 840_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-18",
    title: "Hydration is the most underrated performance hack",
    content: [
      "Even 2% dehydration drops cognitive and physical performance measurably.",
      "Drink a full glass of water before every meal — it regulates appetite naturally.",
      "If your urine is dark, you are already behind on fluids.",
      "Add a pinch of salt and lemon to water for better absorption without sugar.",
    ],
    category: "Diet",
    source: "Hydration Science",
    image_url: null,
    gradient: "ocean",
    created_at: new Date(now - 900_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-19",
    title: "Stop demonizing food groups",
    content: [
      "Carbs fuel workouts; fats regulate hormones; protein rebuilds tissue — you need all three.",
      "Elimination diets work short-term by reducing calories, not by magic.",
      "The best diet is the one that feels sustainable twelve months from now.",
      "Flexibility with food choices prevents the binge-restrict cycle.",
    ],
    category: "Diet",
    source: "Balanced Eating",
    image_url: null,
    gradient: "sunset",
    created_at: new Date(now - 960_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-20",
    title: "Track food for awareness, not obsession",
    content: [
      "Log everything for two weeks — most people have no idea what they actually eat.",
      "You do not need to track forever; the goal is to build intuitive portion sense.",
      "Focus on patterns, not single meals — one bad lunch does not ruin a good week.",
      "If tracking causes anxiety, switch to a photo food journal instead.",
    ],
    category: "Diet",
    source: "Mindful Nutrition",
    image_url:
      "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
    gradient: "aurora",
    created_at: new Date(now - 1_020_000).toISOString(),
  },

  // ── BOOKS (6) ──────────────────────────────────────────────
  {
    ...BASE,
    id: "fallback-4",
    title: "Read for implementation, not completion",
    content: [
      "One applied idea is worth more than ten highlighted pages.",
      "Summarize the chapter in your own words immediately.",
      "Turn every book into one habit, rule, or checklist.",
      "Useful reading changes your calendar, not just your notes.",
    ],
    category: "Books",
    source: "Reading System",
    image_url:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
    gradient: "ocean",
    created_at: new Date(now - 1_080_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-6",
    title: "Small habits deserve visible scoreboards",
    content: [
      "What gets tracked becomes easier to repeat.",
      "Use simple checkmarks instead of complicated systems.",
      "A streak is motivation you can see.",
      "Review weekly so the habit stays connected to results.",
    ],
    category: "Books",
    source: "Atomic Habits Notes",
    image_url:
      "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80",
    gradient: "ocean",
    created_at: new Date(now - 1_140_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-21",
    title: "The obstacle is the way forward",
    content: [
      "Every setback contains data about what needs to change.",
      "Marcus Aurelius ran an empire while journaling about patience — your commute can wait.",
      "Reframe problems as training: this is the rep that builds resilience.",
      "Stoicism is not about suppressing emotion; it is about choosing your response.",
    ],
    category: "Books",
    source: "The Obstacle Is the Way",
    image_url: null,
    gradient: "royal",
    created_at: new Date(now - 1_200_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-22",
    title: "Deep work is a superpower in a distracted world",
    content: [
      "The ability to focus without distraction is becoming the most valuable skill in the economy.",
      "Schedule 2-4 hour blocks for your hardest work with zero notifications.",
      "Shallow work expands to fill the time you give it — timebox ruthlessly.",
      "Train concentration like a muscle: start with 25 minutes and add five each week.",
    ],
    category: "Books",
    source: "Deep Work by Cal Newport",
    image_url: null,
    gradient: "aurora",
    created_at: new Date(now - 1_260_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-23",
    title: "Think in decades, act in days",
    content: [
      "A 10-year vision gives direction; a daily action list gives traction.",
      "Most people overestimate one year and underestimate ten.",
      "Write your ideal future self a letter, then reverse-engineer the first step.",
      "Long-term thinking removes the pressure from any single day.",
    ],
    category: "Books",
    source: "The Almanack of Naval",
    image_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80",
    gradient: "sunset",
    created_at: new Date(now - 1_320_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-24",
    title: "Your environment shapes you more than willpower",
    content: [
      "Redesign your space so good choices are the path of least resistance.",
      "Put running shoes by the door; put the phone charger outside the bedroom.",
      "You do not need more discipline — you need fewer decisions.",
      "Choice architecture is the hidden force behind every lasting habit.",
    ],
    category: "Books",
    source: "Nudge / Atomic Habits",
    image_url: null,
    gradient: "forest",
    created_at: new Date(now - 1_380_000).toISOString(),
  },

  // ── WELLNESS (6) ──────────────────────────────────────────
  {
    ...BASE,
    id: "fallback-25",
    title: "Breathwork is free medicine",
    content: [
      "Four seconds in, seven seconds hold, eight seconds out — instant nervous system reset.",
      "Two minutes of box breathing before a hard conversation changes the outcome.",
      "Your breath is the only autonomic function you can consciously override.",
      "Practice daily and watch your resting heart rate drop within weeks.",
    ],
    category: "Wellness",
    source: "Breathwork Basics",
    image_url:
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    gradient: "ocean",
    created_at: new Date(now - 1_440_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-26",
    title: "Cold exposure builds mental armor",
    content: [
      "A 30-second cold finish to your shower trains your brain to act despite discomfort.",
      "Cold exposure spikes norepinephrine, improving focus and mood for hours.",
      "Start lukewarm and decrease temperature gradually — do not shock yourself on day one.",
      "The hardest part is always the decision to turn the dial; the body adapts fast.",
    ],
    category: "Wellness",
    source: "Hormesis Science",
    image_url: null,
    gradient: "royal",
    created_at: new Date(now - 1_500_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-27",
    title: "Sunlight in the first hour rewires your clock",
    content: [
      "Ten minutes of morning sunlight sets your circadian rhythm for better sleep tonight.",
      "Blue-light glasses at night matter less than real light exposure in the morning.",
      "Outdoor light is 10-100x brighter than indoor light, even on cloudy days.",
      "Consistent light exposure stabilizes mood, energy, and hunger hormones.",
    ],
    category: "Wellness",
    source: "Circadian Health",
    image_url:
      "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1200&q=80",
    gradient: "sunset",
    created_at: new Date(now - 1_560_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-28",
    title: "Journaling clears your mental cache",
    content: [
      "Writing thoughts down moves them from rumination to resolution.",
      "Three pages of stream-of-consciousness in the morning is the original brain dump.",
      "You do not need a fancy journal — a notes app at 6 AM works just fine.",
      "Re-read your entries monthly; patterns you cannot see in the moment become obvious.",
    ],
    category: "Wellness",
    source: "Mental Clarity",
    image_url: null,
    gradient: "aurora",
    created_at: new Date(now - 1_620_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-29",
    title: "Walk more, think better",
    content: [
      "A 20-minute walk increases creative output by up to 60% according to Stanford research.",
      "Walking meetings solve problems faster than sitting in conference rooms.",
      "No headphones, no podcasts — just walk and let your mind wander sometimes.",
      "10,000 steps is not magic, but moving your body every hour is genuinely transformative.",
    ],
    category: "Wellness",
    source: "Movement Science",
    image_url:
      "https://images.unsplash.com/photo-1476231682828-37e571bc172f?auto=format&fit=crop&w=1200&q=80",
    gradient: "forest",
    created_at: new Date(now - 1_680_000).toISOString(),
  },
  {
    ...BASE,
    id: "fallback-30",
    title: "Digital detox is not a trend — it is hygiene",
    content: [
      "Your phone checks you more than you check it — screen time data does not lie.",
      "Set a hard cutoff: no screens one hour before bed and you will sleep deeper.",
      "Replace infinite scrolling with a physical book or a real conversation.",
      "One phone-free day per week resets your attention span more than any app ever will.",
    ],
    category: "Wellness",
    source: "Digital Wellness",
    image_url: null,
    gradient: "royal",
    created_at: new Date(now - 1_740_000).toISOString(),
  },
];

export function getFallbackPosts() {
  return fallbackPosts;
}
